ALTER TABLE users ADD COLUMN IF NOT EXISTS department VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS "position" VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role_id VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS role_name VARCHAR(100);

CREATE INDEX IF NOT EXISTS users_department_idx ON users(department);
